// Generated by scripts/build-changelog.mjs — do not edit by hand. Run `npm run build-changelog`.
export interface ChangelogSection
{
	label:   string;
	changes: string[];
}

export interface ChangelogEntry
{
	version:  string;
	date:     string | null;
	sections: ChangelogSection[];
}

export const changelog: ChangelogEntry[] = [
	{
		'version': 'Unreleased',
		'date': null,
		'sections': [
			{
				'label': 'Added',
				'changes': [
					'Add and enhance library components',
					'Add blocks system to library, cli, and docs site',
					'Add accessibility audit command to cli',
					'Add live code playground to docs site',
					'Add changelog page to docs site',
					'Restructure docs site navigation shell'
				]
			},
			{
				'label': 'Changed',
				'changes': [
					'Add codemirror, react-hook-form, and changelog script deps'
				]
			},
			{
				'label': 'Docs',
				'changes': [
					'Add cli package readme',
					'Update rules and patterns for new components and blocks'
				]
			}
		]
	},
	{
		'version': '0.1.0',
		'date': '2026-06-18',
		'sections': [
			{
				'label': 'Added',
				'changes': [
					'Initial component library, accordion, and storybook organization',
					'Add new components and documentation site',
					'Add new components and update existing',
					'Add open source section, contributing guide, and seo improvements',
					'Add 9 new components including modal, drawer, and tooltip',
					'Overhaul themes — add ocean/ember/forest/noir/plum, remove old set',
					'Add token pipeline with json source files and build script',
					'Add container queries to card and datatable',
					'Add graph and typewriter components',
					'Add surface style system and update component implementations',
					'Overhaul docs site with style switcher, mobile nav, and new pages',
					'Add cli package and update project config and rules',
					'Add loading state and icon size variant to button',
					'Add audioplayer, tilt, and workflowbuilder components',
					'Expand mcp server with registry tools, rules resource, and prompts',
					'Register audioplayer, tilt, and workflowbuilder in docs registry'
				]
			},
			{
				'label': 'Fixed',
				'changes': [
					'Prevent duplicate key warnings in datatable columns',
					'Migrate modal and drawer to native dialog element',
					'Portal popover, tooltip, and dropdown for viewport-safe positioning',
					'Improve togglegroup roving tabindex and datepicker focus management',
					'Use brand-fg in timeline dot and opaque danger tokens in toast',
					'Correct brand.fg contrast and widen surface hover state ramps',
					'Codeblock focus, otpinput autocomplete, canvas token, color ban',
					'Exclude packages from root tsconfig to fix ci build',
					'Add missing effect dep array in modal and null guard in mosaic',
					'Pre-publish audit — a11y, cli tokens, dead code, and exports'
				]
			},
			{
				'label': 'Changed',
				'changes': [
					'Add lint to pre-commit hook',
					'Add vercel config, typecheck, and storybook build to ci',
					'Add typecheck to pre-commit and ci, add vercel config',
					'Remove storybook, update tooling and dependencies',
					'Update existing components and remove calendarinput',
					'Update vercel config for next.js deployment',
					'Add component completeness validation to ci and pre-commit',
					'Move docs components and registry from src/docs to app/_docs',
					'Move mcp server from mcp/ into app/api/mcp route handler',
					'Export new components from src/index.ts',
					'Update app pages, globals.css, layout, and next config',
					'Update rules and docs for new app/_docs directory structure',
					'Remove unused public assets and vitest shims',
					'Add dialog styles, scrollbar-gutter, text-wrap, and danger tokens',
					'Add token contrast gate script and wire into ci',
					'Add contrast check step to ci workflow',
					'Ignore editor swap files and cli package-lock',
					'Update ci, cli registry, and validate-components',
					'Add vercel security headers and update docs branding'
				]
			},
			{
				'label': 'Docs',
				'changes': [
					'Add accessibility patterns and update rule files',
					'Add missing spec files for 9 components',
					'Update patterns, rules, agents, and docs site registry',
					'Update mcp and skill pages for new tools and prompts',
					'Fix copy in pattern docs and input spec'
				]
			}
		]
	}
];
