import { readdirSync, readFileSync, writeFileSync, existsSync, statSync } from 'fs';
import { log } from '@clack/prompts';
import { resolve } from 'path';
import pc from 'picocolors';

interface ParsedExports
{
	defaultName: string | null;
	namedValues: string[];
	namedTypes: string[];
}

const BARREL_HEADER = '// Auto-generated by dafink-ui — regenerated on every `add`, do not edit directly.\n';

function parseExports(source: string): ParsedExports
{
	const defaultMatch =
		source.match(/^export default function\s+(\w+)/m) ??
		source.match(/^export default class\s+(\w+)/m) ??
		source.match(/^export default (\w+);/m);

	const namedValues = [
		...source.matchAll(/^export const (\w+)/gm),
		...source.matchAll(/^export function (\w+)/gm),
	].map(match => match[1]);

	const namedTypes = [
		...source.matchAll(/^export interface (\w+)/gm),
		...source.matchAll(/^export type (\w+)/gm),
	].map(match => match[1]);

	return { defaultName: defaultMatch ? defaultMatch[1] : null, namedValues, namedTypes };
}

function scanComponentFolder(componentsDir: string, folder: string): ParsedExports | null
{
	const filePath = resolve(componentsDir, folder, `${folder}.tsx`);
	if(!existsSync(filePath)) return null;

	return parseExports(readFileSync(filePath, 'utf8'));
}

function listComponentFolders(componentsDir: string): string[]
{
	return readdirSync(componentsDir)
		.filter(name => statSync(resolve(componentsDir, name)).isDirectory())
		.sort();
}

function buildExportLines(componentsDir: string, folders: string[]): string[]
{
	const usedValueNames = new Set<string>();
	const usedTypeNames = new Set<string>();
	const lines: string[] = [];

	for(const folder of folders)
	{
		const parsed = scanComponentFolder(componentsDir, folder);
		if(!parsed) continue;

		const modulePath = `./${folder}/${folder}`;
		const valueExports: string[] = [];

		if(parsed.defaultName)
		{
			if(usedValueNames.has(folder))
				log.warn(pc.yellow(`Barrel: skipping duplicate export "${folder}" from ${modulePath}`));
			else
			{
				usedValueNames.add(folder);
				valueExports.push(`default as ${folder}`);
			}
		}

		for(const name of parsed.namedValues)
		{
			if(usedValueNames.has(name))
			{
				log.warn(pc.yellow(`Barrel: skipping duplicate export "${name}" from ${modulePath}`));
				continue;
			}

			usedValueNames.add(name);
			valueExports.push(name);
		}

		if(valueExports.length > 0)
			lines.push(`export { ${valueExports.join(', ')} } from '${modulePath}';`);

		const typeExports: string[] = [];

		for(const name of parsed.namedTypes)
		{
			if(usedTypeNames.has(name))
			{
				log.warn(pc.yellow(`Barrel: skipping duplicate type export "${name}" from ${modulePath}`));
				continue;
			}

			usedTypeNames.add(name);
			typeExports.push(name);
		}

		if(typeExports.length > 0)
			lines.push(`export type { ${typeExports.join(', ')} } from '${modulePath}';`);
	}

	return lines;
}

export function generateBarrel(componentsDir: string): void
{
	if(!existsSync(componentsDir)) return;

	const folders = listComponentFolders(componentsDir);
	const lines = buildExportLines(componentsDir, folders);
	const content = lines.length > 0 ? `${BARREL_HEADER}\n${lines.join('\n')}\n` : BARREL_HEADER;

	writeFileSync(resolve(componentsDir, 'index.ts'), content, 'utf8');

	log.info(pc.dim(`index.ts regenerated with ${lines.length} export statement(s)`));
}
