// AUTO-GENERATED by packages/cli/scripts/build-registry.mjs — do not edit by hand.
// Source of truth: app/_docs/registry/ (index.ts for components, blocks.ts for blocks).
// Run `npm run sync-registry` from the repo root to regenerate this file.

export interface BlockRegistryEntry
{
	name: string;
	slug: string;
	files: string[];
	deps: string[];
	registryDependencies: string[];
}

export const BLOCKS_REGISTRY: BlockRegistryEntry[] = [
	{ name: 'Dashboard', slug: 'dashboard', files: ['Dashboard/Dashboard.tsx'], deps: ['recharts'], registryDependencies: ['mosaic', 'dropdown-menu', 'charts', 'badge', 'avatar', 'data-table', 'count-up'] },
	{ name: 'Auth form', slug: 'auth-form', files: ['AuthForm/AuthForm.tsx'], deps: [], registryDependencies: ['card', 'form', 'toggle-group', 'checkbox', 'otp-input', 'progress', 'button', 'badge', 'input'] },
	{ name: 'Settings form', slug: 'settings-form', files: ['SettingsForm/SettingsForm.tsx'], deps: [], registryDependencies: ['card', 'form', 'input', 'textarea', 'switch', 'select', 'button', 'badge'] },
	{ name: 'Onboarding checklist', slug: 'onboarding-checklist', files: ['OnboardingChecklist/OnboardingChecklist.tsx'], deps: [], registryDependencies: ['card', 'checkbox', 'progress', 'button'] },
	{ name: 'Checkout form', slug: 'checkout-form', files: ['CheckoutForm/CheckoutForm.tsx'], deps: [], registryDependencies: ['card', 'form', 'radio', 'button', 'input'] },
	{ name: 'Pricing section', slug: 'pricing-section', files: ['PricingSection/PricingSection.tsx'], deps: [], registryDependencies: ['accordion', 'toggle-group', 'card', 'button', 'badge'] },
	{ name: 'Notifications panel', slug: 'notifications-panel', files: ['NotificationsPanel/NotificationsPanel.tsx'], deps: [], registryDependencies: ['card', 'scroll-fade', 'avatar', 'button'] },
	{ name: 'Team grid', slug: 'team-grid', files: ['TeamGrid/TeamGrid.tsx'], deps: [], registryDependencies: ['badge', 'card', 'avatar'] },
	{ name: 'Chart card', slug: 'chart-card', files: ['ChartCard/ChartCard.tsx'], deps: [], registryDependencies: ['card', 'charts', 'count-up', 'badge'] },
	{ name: 'AI chat', slug: 'ai-chat', files: ['AiChat/AiChat.tsx'], deps: [], registryDependencies: ['card', 'scroll-fade', 'message', 'avatar', 'button', 'badge', 'input'] },
	{ name: 'Team management', slug: 'team-management', files: ['TeamManagement/TeamManagement.tsx'], deps: [], registryDependencies: ['modal', 'card', 'select', 'badge', 'avatar', 'button', 'input'] },
	{ name: 'Social login', slug: 'auth-form-social', files: ['AuthFormSocial/AuthFormSocial.tsx'], deps: [], registryDependencies: ['card', 'form', 'button', 'badge', 'input'] },
	{ name: 'Magic link', slug: 'auth-form-magic-link', files: ['AuthFormMagicLink/AuthFormMagicLink.tsx'], deps: [], registryDependencies: ['card', 'form', 'button', 'input'] },
	{ name: 'Team skill radar', slug: 'chart-card-radar', files: ['ChartCardRadar/ChartCardRadar.tsx'], deps: [], registryDependencies: ['card', 'charts', 'count-up', 'badge'] },
	{ name: 'Top products', slug: 'chart-card-bar', files: ['ChartCardBar/ChartCardBar.tsx'], deps: [], registryDependencies: ['card', 'charts', 'count-up', 'badge'] },
	{ name: 'Usage-based pricing', slug: 'pricing-section-usage', files: ['PricingSectionUsage/PricingSectionUsage.tsx'], deps: [], registryDependencies: ['card', 'slider', 'button', 'badge'] },
	{ name: 'Filterable with actions', slug: 'notifications-panel-actionable', files: ['NotificationsPanelActionable/NotificationsPanelActionable.tsx'], deps: [], registryDependencies: ['tabs', 'card', 'scroll-fade', 'button', 'badge'] },
];

export function findBlockBySlug(slug: string): BlockRegistryEntry | undefined
{
	return BLOCKS_REGISTRY.find(e => e.slug === slug);
}

export function findBlockByName(name: string): BlockRegistryEntry | undefined
{
	return BLOCKS_REGISTRY.find(e => e.name.toLowerCase() === name.toLowerCase());
}

export function resolveBlock(input: string): BlockRegistryEntry | undefined
{
	return findBlockBySlug(input) ?? findBlockByName(input);
}
