// Hand-authored surface style. Styles are NOT generated by `npm run tokens`
// (that pipeline owns color palettes); they live here as plain TS.
import type { Style } from './types';

const vars = {
	'--radius-sm':     '0.375rem',
	'--radius':        '0.5rem',
	'--radius-lg':     '0.75rem',
	'--border-width':  '1px',
	'--shadow-sm':     '0 1px 2px 0 rgb(0 0 0 / 0.05)',
	'--shadow':        '0 1px 3px 0 rgb(0 0 0 / 0.10), 0 1px 2px -1px rgb(0 0 0 / 0.10)',
	'--shadow-lg':     '0 10px 15px -3px rgb(0 0 0 / 0.10), 0 4px 6px -4px rgb(0 0 0 / 0.10)',
	'--backdrop-blur': '0px',
	'--surface-alpha': '1',
	'--inner-shadow':  'none',
};

export const minimalStyle: Style =
{
	name:        'minimal',
	label:       'Minimal',
	description: 'Restrained radius, hairline borders, soft shadow. The clean default.',
	light:       vars,
	dark:        vars,
};
