// AUTO-GENERATED — edit tokens/ember.{light,dark}.json then run `npm run tokens`
import type { Theme } from './types';

export const emberTheme: Theme =
{
	name:   'ember',
	label:  'Ember',
	accent: '#fb923c',

	light:
	{
		'--color-brand':                 '#ea580c',
		'--color-brand-hover':           '#c2410c',
		'--color-brand-active':          '#9a3412',
		'--color-brand-ring':            '#ea580c',
		'--color-brand-fg':              '#ffffff',
		'--color-danger':                '#dc2626',
		'--color-danger-hover':          '#b91c1c',
		'--color-danger-active':         '#991b1b',
		'--color-danger-ring':           '#dc2626',
		'--color-success':               '#16a34a',
		'--color-success-bg':            '#f0fdf4',
		'--color-success-border':        '#bbf7d0',
		'--color-warning':               '#ca8a04',
		'--color-warning-bg':            '#fefce8',
		'--color-warning-border':        '#fef08a',
		'--color-surface':               '#ffffff',
		'--color-surface-hover':         '#fff7ed',
		'--color-surface-active':        '#ffedd5',
		'--color-surface-border':        '#fed7aa',
		'--color-surface-border-hover':  '#fdba74',
		'--color-text':                  '#431407',
		'--color-text-muted':            '#9a3412',
		'--color-text-subtle':           '#fdba74',
		'--color-text-inverted':         '#ffffff',
		'--color-input-border':          '#fed7aa',
		'--color-input-border-hover':    '#fdba74',
		'--color-input-ring':            '#ea580c',
		'--color-input-placeholder':     '#fdba74',
		'--color-input-disabled-bg':     '#ffedd5',
		'--color-input-disabled-text':   '#fdba74',
		'--color-input-error':           '#dc2626',
		'--color-input-error-ring':      '#dc2626',
	},

	dark:
	{
		'--color-brand':                 '#fb923c',
		'--color-brand-hover':           '#fdba74',
		'--color-brand-active':          '#fed7aa',
		'--color-brand-ring':            '#fb923c',
		'--color-brand-fg':              '#431407',
		'--color-danger':                '#f87171',
		'--color-danger-hover':          '#fca5a5',
		'--color-danger-active':         '#fecaca',
		'--color-danger-ring':           '#f87171',
		'--color-success':               '#4ade80',
		'--color-success-bg':            '#052e16',
		'--color-success-border':        '#166534',
		'--color-warning':               '#fde047',
		'--color-warning-bg':            '#1c1000',
		'--color-warning-border':        '#713f12',
		'--color-surface':               '#150800',
		'--color-surface-hover':         '#220d00',
		'--color-surface-active':        '#2f1400',
		'--color-surface-border':        '#3d1d00',
		'--color-surface-border-hover':  '#522900',
		'--color-text':                  '#ffedd5',
		'--color-text-muted':            '#fb923c',
		'--color-text-subtle':           '#3d1d00',
		'--color-text-inverted':         '#150800',
		'--color-input-border':          '#3d1d00',
		'--color-input-border-hover':    '#522900',
		'--color-input-ring':            '#fb923c',
		'--color-input-placeholder':     '#3d1d00',
		'--color-input-disabled-bg':     '#220d00',
		'--color-input-disabled-text':   '#3d1d00',
		'--color-input-error':           '#f87171',
		'--color-input-error-ring':      '#f87171',
	},
};
