// AUTO-GENERATED — edit tokens/forest.{light,dark}.json then run `npm run tokens`
import type { Theme } from './types';

export const forestTheme: Theme =
{
	name:   'forest',
	label:  'Forest',
	accent: '#4ade80',

	light:
	{
		'--color-brand':                 '#16a34a',
		'--color-brand-hover':           '#15803d',
		'--color-brand-active':          '#166534',
		'--color-brand-ring':            '#16a34a',
		'--color-brand-fg':              '#ffffff',
		'--color-danger':                '#dc2626',
		'--color-danger-hover':          '#b91c1c',
		'--color-danger-active':         '#991b1b',
		'--color-danger-ring':           '#dc2626',
		'--color-success':               '#16a34a',
		'--color-success-bg':            '#f0fdf4',
		'--color-success-border':        '#bbf7d0',
		'--color-warning':               '#d97706',
		'--color-warning-bg':            '#fffbeb',
		'--color-warning-border':        '#fde68a',
		'--color-surface':               '#ffffff',
		'--color-surface-hover':         '#f0fdf4',
		'--color-surface-active':        '#dcfce7',
		'--color-surface-border':        '#bbf7d0',
		'--color-surface-border-hover':  '#86efac',
		'--color-text':                  '#14532d',
		'--color-text-muted':            '#166534',
		'--color-text-subtle':           '#86efac',
		'--color-text-inverted':         '#ffffff',
		'--color-input-border':          '#bbf7d0',
		'--color-input-border-hover':    '#86efac',
		'--color-input-ring':            '#16a34a',
		'--color-input-placeholder':     '#86efac',
		'--color-input-disabled-bg':     '#dcfce7',
		'--color-input-disabled-text':   '#86efac',
		'--color-input-error':           '#dc2626',
		'--color-input-error-ring':      '#dc2626',
	},

	dark:
	{
		'--color-brand':                 '#4ade80',
		'--color-brand-hover':           '#86efac',
		'--color-brand-active':          '#bbf7d0',
		'--color-brand-ring':            '#4ade80',
		'--color-brand-fg':              '#14532d',
		'--color-danger':                '#f87171',
		'--color-danger-hover':          '#fca5a5',
		'--color-danger-active':         '#fecaca',
		'--color-danger-ring':           '#f87171',
		'--color-success':               '#4ade80',
		'--color-success-bg':            '#052e16',
		'--color-success-border':        '#166534',
		'--color-warning':               '#fbbf24',
		'--color-warning-bg':            '#1c1200',
		'--color-warning-border':        '#92400e',
		'--color-surface':               '#020d06',
		'--color-surface-hover':         '#041508',
		'--color-surface-active':        '#071d0c',
		'--color-surface-border':        '#0c2c14',
		'--color-surface-border-hover':  '#13431e',
		'--color-text':                  '#dcfce7',
		'--color-text-muted':            '#4ade80',
		'--color-text-subtle':           '#0c2c14',
		'--color-text-inverted':         '#020d06',
		'--color-input-border':          '#0c2c14',
		'--color-input-border-hover':    '#13431e',
		'--color-input-ring':            '#4ade80',
		'--color-input-placeholder':     '#0c2c14',
		'--color-input-disabled-bg':     '#041508',
		'--color-input-disabled-text':   '#0c2c14',
		'--color-input-error':           '#f87171',
		'--color-input-error-ring':      '#f87171',
	},
};
