// AUTO-GENERATED — edit tokens/noir.{light,dark}.json then run `npm run tokens`
import type { Theme } from './types';

export const noirTheme: Theme =
{
	name:   'noir',
	label:  'Noir',
	accent: '#64748b',

	light:
	{
		'--color-brand':                 '#1e293b',
		'--color-brand-hover':           '#334155',
		'--color-brand-active':          '#475569',
		'--color-brand-ring':            '#1e293b',
		'--color-brand-fg':              '#ffffff',
		'--color-danger':                '#dc2626',
		'--color-danger-hover':          '#b91c1c',
		'--color-danger-active':         '#991b1b',
		'--color-danger-ring':           '#dc2626',
		'--color-success':               '#16a34a',
		'--color-success-bg':            '#f0fdf4',
		'--color-success-border':        '#bbf7d0',
		'--color-warning':               '#d97706',
		'--color-warning-bg':            '#fffbeb',
		'--color-warning-border':        '#fde68a',
		'--color-surface':               '#f8fafc',
		'--color-surface-hover':         '#f1f5f9',
		'--color-surface-active':        '#e2e8f0',
		'--color-surface-border':        '#cbd5e1',
		'--color-surface-border-hover':  '#94a3b8',
		'--color-text':                  '#0f172a',
		'--color-text-muted':            '#475569',
		'--color-text-subtle':           '#94a3b8',
		'--color-text-inverted':         '#ffffff',
		'--color-input-border':          '#cbd5e1',
		'--color-input-border-hover':    '#94a3b8',
		'--color-input-ring':            '#1e293b',
		'--color-input-placeholder':     '#94a3b8',
		'--color-input-disabled-bg':     '#e2e8f0',
		'--color-input-disabled-text':   '#94a3b8',
		'--color-input-error':           '#dc2626',
		'--color-input-error-ring':      '#dc2626',
	},

	dark:
	{
		'--color-brand':                 '#f1f5f9',
		'--color-brand-hover':           '#e2e8f0',
		'--color-brand-active':          '#cbd5e1',
		'--color-brand-ring':            '#f1f5f9',
		'--color-brand-fg':              '#0f172a',
		'--color-danger':                '#f87171',
		'--color-danger-hover':          '#fca5a5',
		'--color-danger-active':         '#fecaca',
		'--color-danger-ring':           '#f87171',
		'--color-success':               '#4ade80',
		'--color-success-bg':            '#052e16',
		'--color-success-border':        '#166534',
		'--color-warning':               '#fbbf24',
		'--color-warning-bg':            '#1c1200',
		'--color-warning-border':        '#92400e',
		'--color-surface':               '#020617',
		'--color-surface-hover':         '#0f172a',
		'--color-surface-active':        '#1e293b',
		'--color-surface-border':        '#1e293b',
		'--color-surface-border-hover':  '#334155',
		'--color-text':                  '#f1f5f9',
		'--color-text-muted':            '#94a3b8',
		'--color-text-subtle':           '#1e293b',
		'--color-text-inverted':         '#020617',
		'--color-input-border':          '#1e293b',
		'--color-input-border-hover':    '#334155',
		'--color-input-ring':            '#f1f5f9',
		'--color-input-placeholder':     '#334155',
		'--color-input-disabled-bg':     '#0f172a',
		'--color-input-disabled-text':   '#1e293b',
		'--color-input-error':           '#f87171',
		'--color-input-error-ring':      '#f87171',
	},
};
