// AUTO-GENERATED — edit tokens/ocean.{light,dark}.json then run `npm run tokens`
import type { Theme } from './types';

export const oceanTheme: Theme =
{
	name:   'ocean',
	label:  'Ocean',
	accent: '#38bdf8',

	light:
	{
		'--color-brand':                 '#0284c7',
		'--color-brand-hover':           '#0369a1',
		'--color-brand-active':          '#075985',
		'--color-brand-ring':            '#0284c7',
		'--color-brand-fg':              '#ffffff',
		'--color-danger':                '#dc2626',
		'--color-danger-hover':          '#b91c1c',
		'--color-danger-active':         '#991b1b',
		'--color-danger-ring':           '#dc2626',
		'--color-success':               '#16a34a',
		'--color-success-bg':            '#f0fdf4',
		'--color-success-border':        '#bbf7d0',
		'--color-warning':               '#d97706',
		'--color-warning-bg':            '#fffbeb',
		'--color-warning-border':        '#fde68a',
		'--color-surface':               '#ffffff',
		'--color-surface-hover':         '#f0f9ff',
		'--color-surface-active':        '#e0f2fe',
		'--color-surface-border':        '#bae6fd',
		'--color-surface-border-hover':  '#7dd3fc',
		'--color-text':                  '#0c4a6e',
		'--color-text-muted':            '#0369a1',
		'--color-text-subtle':           '#93c5fd',
		'--color-text-inverted':         '#ffffff',
		'--color-input-border':          '#bae6fd',
		'--color-input-border-hover':    '#7dd3fc',
		'--color-input-ring':            '#0284c7',
		'--color-input-placeholder':     '#93c5fd',
		'--color-input-disabled-bg':     '#e0f2fe',
		'--color-input-disabled-text':   '#93c5fd',
		'--color-input-error':           '#dc2626',
		'--color-input-error-ring':      '#dc2626',
	},

	dark:
	{
		'--color-brand':                 '#38bdf8',
		'--color-brand-hover':           '#7dd3fc',
		'--color-brand-active':          '#bae6fd',
		'--color-brand-ring':            '#38bdf8',
		'--color-brand-fg':              '#0c4a6e',
		'--color-danger':                '#f87171',
		'--color-danger-hover':          '#fca5a5',
		'--color-danger-active':         '#fecaca',
		'--color-danger-ring':           '#f87171',
		'--color-success':               '#4ade80',
		'--color-success-bg':            '#052e16',
		'--color-success-border':        '#166534',
		'--color-warning':               '#fbbf24',
		'--color-warning-bg':            '#1c1200',
		'--color-warning-border':        '#92400e',
		'--color-surface':               '#040d14',
		'--color-surface-hover':         '#071628',
		'--color-surface-active':        '#0c2040',
		'--color-surface-border':        '#102a4c',
		'--color-surface-border-hover':  '#1a3f6f',
		'--color-text':                  '#e0f2fe',
		'--color-text-muted':            '#7dd3fc',
		'--color-text-subtle':           '#102a4c',
		'--color-text-inverted':         '#040d14',
		'--color-input-border':          '#102a4c',
		'--color-input-border-hover':    '#1a3f6f',
		'--color-input-ring':            '#38bdf8',
		'--color-input-placeholder':     '#102a4c',
		'--color-input-disabled-bg':     '#071628',
		'--color-input-disabled-text':   '#102a4c',
		'--color-input-error':           '#f87171',
		'--color-input-error-ring':      '#f87171',
	},
};
