// AUTO-GENERATED — edit tokens/plum.{light,dark}.json then run `npm run tokens`
import type { Theme } from './types';

export const plumTheme: Theme =
{
	name:   'plum',
	label:  'Plum',
	accent: '#a78bfa',

	light:
	{
		'--color-brand':                 '#7c3aed',
		'--color-brand-hover':           '#6d28d9',
		'--color-brand-active':          '#5b21b6',
		'--color-brand-ring':            '#7c3aed',
		'--color-brand-fg':              '#ffffff',
		'--color-danger':                '#dc2626',
		'--color-danger-hover':          '#b91c1c',
		'--color-danger-active':         '#991b1b',
		'--color-danger-ring':           '#dc2626',
		'--color-success':               '#16a34a',
		'--color-success-bg':            '#f0fdf4',
		'--color-success-border':        '#bbf7d0',
		'--color-warning':               '#d97706',
		'--color-warning-bg':            '#fffbeb',
		'--color-warning-border':        '#fde68a',
		'--color-surface':               '#ffffff',
		'--color-surface-hover':         '#f5f3ff',
		'--color-surface-active':        '#ede9fe',
		'--color-surface-border':        '#ddd6fe',
		'--color-surface-border-hover':  '#c4b5fd',
		'--color-text':                  '#2e1065',
		'--color-text-muted':            '#5b21b6',
		'--color-text-subtle':           '#c4b5fd',
		'--color-text-inverted':         '#ffffff',
		'--color-input-border':          '#ddd6fe',
		'--color-input-border-hover':    '#c4b5fd',
		'--color-input-ring':            '#7c3aed',
		'--color-input-placeholder':     '#c4b5fd',
		'--color-input-disabled-bg':     '#ede9fe',
		'--color-input-disabled-text':   '#c4b5fd',
		'--color-input-error':           '#dc2626',
		'--color-input-error-ring':      '#dc2626',
	},

	dark:
	{
		'--color-brand':                 '#a78bfa',
		'--color-brand-hover':           '#c4b5fd',
		'--color-brand-active':          '#ddd6fe',
		'--color-brand-ring':            '#a78bfa',
		'--color-brand-fg':              '#2e1065',
		'--color-danger':                '#f87171',
		'--color-danger-hover':          '#fca5a5',
		'--color-danger-active':         '#fecaca',
		'--color-danger-ring':           '#f87171',
		'--color-success':               '#4ade80',
		'--color-success-bg':            '#052e16',
		'--color-success-border':        '#166534',
		'--color-warning':               '#fbbf24',
		'--color-warning-bg':            '#1c1200',
		'--color-warning-border':        '#92400e',
		'--color-surface':               '#080412',
		'--color-surface-hover':         '#0f0920',
		'--color-surface-active':        '#190e30',
		'--color-surface-border':        '#251546',
		'--color-surface-border-hover':  '#321e5e',
		'--color-text':                  '#ede9fe',
		'--color-text-muted':            '#a78bfa',
		'--color-text-subtle':           '#251546',
		'--color-text-inverted':         '#080412',
		'--color-input-border':          '#251546',
		'--color-input-border-hover':    '#321e5e',
		'--color-input-ring':            '#a78bfa',
		'--color-input-placeholder':     '#251546',
		'--color-input-disabled-bg':     '#0f0920',
		'--color-input-disabled-text':   '#251546',
		'--color-input-error':           '#f87171',
		'--color-input-error-ring':      '#f87171',
	},
};
